name: statistics-resampling-online
channels:
  - conda-forge
dependencies:
  - nbgitpuller == 1.2.0
  - nano == 7.2
  # GNU Octave for JupyterLab
  # Octave 8.3 is the latest version to work with the same dependencies as R 4.1.3
  - octave == 8.3 
  - octave_kernel == 0.35.1
  # For compiling packages
  - compilers == 1.7.0
  - make == 4.3
  # Python
  - python == 3.10.12
  - ipyparallel == 8.6.1
  - json5 == 0.9.22
  - jsonschema == 4.21.1
  - jsonschema-specifications == 2023.12.1
  - jsonschema-with-format-nongpl == 4.21.1
  - ipysheet == 0.7.0
  - numpy == 1.23.1
  - scipy == 1.12.0
  - plotnine == 0.13.0
  - plotly == 5.19.0
  - scikit-learn
  - seaborn
  - matplotlib
  - statsmodels
  - tensorflow
  - keras
  # R (including package manager)
  # R 4.1.3 is the latest version to use R_GE_version == 14, which is compatible with RStudio server 2022.12.0+353 on binder
  # Packages not available via conda-forge are installed using install.R
  - r-essentials == 4.1
  - r-markdown == 1.7
  - r-bootstrap == 2019.6
  - r-png == 0.1_8
  - r-ggforce == 0.4.1
  - r-gridextra == 2.3
  - r-gridsvg == 1.7_5
  - r-hmisc == 5.1_0
  - r-ggsignif == 0.6.4
  - r-car == 3.1_2
  - r-lmperm == 2.1.0
  - r-lme4 == 1.1_33
  - r-lmertest == 3.1_3
  - r-parameters == 0.21.1
  - r-emmeans == 1.8.6
  - r-multcomp == 1.4_23
  - r-plotly == 4.10.2
  - r-afex 
  - r-rcartocolor
  - r-broom.mixed
  - r-effectsize 
  - r-kableextra
  - r-lavaan
  - r-insight
  - r-learnr
  - r-learnbayes
  - r-qqplotr
  - r-performance
  - r-mlr3
  - r-tidymodels
  - r-gparotation
  - r-psych
  - r-effsize
  - r-gt
  - r-ggraph
  - r-ggally
  - r-ggfortify
  - r-ggrepel
  - r-ggdist
  - r-ggridges
  - r-ggbeeswarm
  - r-gghalves
  - r-ggpubr
  - r-cowplot
  - r-lmvar
  - r-multcompview
  - r-compute.es
  - r-pastecs
  - r-here
  - r-robust
  - r-robustbase
  - r-wrs2
  - r-sjstats
  - r-effects
  - r-aiccmodavg
  - r-correlation
  - r-interactions
  - r-modelbased
  - r-brms
  - r-bayesfactor
  - r-tidybayes
  - r-logspline
  - r-tensorflow
  - r-keras
  # Jupyter Lab extensions
  - jupyter-archive == 3.4.0
  - jupyter-offlinenotebook == 0.3.1
  - jupyterlab-spreadsheet-editor == 0.6.1
  - jupyterlab-drawio == 0.9.0
  - jupyterlab-latex == 3.1.0
  # - jupyterlab-filesystem-access == 0.5.3 
