channels:
  - conda-forge
dependencies:
  - nbgitpuller == 1.2.0
  - nano == 7.2
  # GNU Octave for JupyterLab
  # Octave 8.3 is the latest version to work with the same dependencies as R 4.1.3
  - octave == 8.3 
  - octave_kernel == 0.35.1
  # For compiling packages
  - compilers == 1.7.0
  - make == 4.3
  # Python
  - python == 3.10.12
  - ipyparallel == 8.6.1
  - json5 == 0.9.22
  - jsonschema == 4.21.1
  - jsonschema-specifications == 2023.12.1
  - jsonschema-with-format-nongpl == 4.21.1
  - ipysheet == 0.7.0
  - numpy == 1.23.1
  - scipy == 1.12.0
  - mpmath == 1.3.0
  - plotnine == 0.13.0
  - plotly == 5.19.0
  - seaborn == 0.13.2
  - matplotlib == 3.8.3
  - statsmodels == 0.14.1
  - resample == 1.7.1
  - scikit-learn == 1.4.1.post1
  # R (including package manager)
  # R 4.1.3 is the latest version to use R_GE_version == 14, which is compatible with RStudio server 2022.12.0+353 on binder
  # Packages not available via conda-forge are installed using install.R
  - r-essentials == 4.1
  - r-markdown == 1.7
  - r-bootstrap == 2019.6
  - r-png == 0.1_8
  - r-ggforce == 0.4.1
  - r-gridextra == 2.3
  - r-gridsvg == 1.7_5
  - r-hmisc == 5.1_0
  - r-ggsignif == 0.6.4
  - r-car == 3.1_2
  - r-insight == 0.19.2
  - r-lmperm == 2.1.0
  - r-lme4 == 1.1_33
  - r-lmertest == 3.1_3
  - r-parameters == 0.21.1
  - r-emmeans == 1.8.6
  - r-multcomp == 1.4_23
  - r-plotly == 4.10.2
  - r-afex == 1.3_0
  - r-rcartocolor == 2.1.1
  - r-broom.mixed == 0.2.9.4
  - r-effectsize == 0.8.3
  - r-effects == 4.2_2
  - r-effsize == 0.8.1
  - r-kableextra == 1.3.4
  - r-lavaan == 0.6_15
  - r-learnr == 0.11.4
  - r-learnbayes == 2.15.1
  - r-qqplotr == 0.0.6
  - r-performance == 0.10.4
  - r-reticulate == 1.30
  - r-mlr3 == 0.16.0
  - r-tidymodels == 1.1.0
  - r-gparotation == 2023.3_1
  - r-psych == 2.3.3
  - r-gt == 0.9.0
  - r-ggraph == 2.1.0
  - r-ggally == 2.1.2
  - r-ggfortify == 0.4.16
  - r-ggrepel == 0.9.3
  - r-ggdist == 3.3.0
  - r-ggridges == 0.5.4
  - r-ggbeeswarm == 0.7.2
  - r-gghalves == 0.1.4
  - r-ggpubr == 0.6.0
  - r-cowplot == 1.1.1
  - r-lmvar == 1.5.2
  - r-multcompview == 0.1_9
  - r-compute.es == 0.2_5
  - r-pastecs == 1.3.21
  - r-here == 1.0.1
  - r-robust == 0.7_1
  - r-robustbase == 0.95_1
  - r-wrs2 == 1.1_4
  - r-sjstats == 0.18.2
  - r-aiccmodavg == 2.3_2
  - r-correlation == 0.8.4
  - r-interactions == 1.1.5
  - r-modelbased == 0.8.6
  - r-brms == 2.19.0
  - r-bayesfactor == 0.9.12_4.4
  - r-tidybayes == 3.0.4
  - r-logspline == 2.1.19
  # Jupyter Lab extensions
  - jupyter-archive == 3.3.4
  - jupyter-offlinenotebook == 0.3.1
  - jupyterlab-spreadsheet-editor == 0.6.1
  - jupyterlab-drawio == 0.9.0
  - jupyterlab-latex == 3.1.0
  - webio-jupyter-extension = 0.1.0
  #- jupyterlab-filesystem-access == 0.5.3 
  #- jupyterlab-fileopen == 0.2.2
