#!/bin/bash

# Fail fast
set -o errexit
set -o nounset

# Uninstall jupyter-offlinenotebook extension since the 'Download' button function is buggy
# Download/upload to/from browser storage then download from the 'File' menu instead
# micromamba remove -yn notebook jupyter-offlinenotebook

# Installation of Octave packages is dependent on current user.
# This works because postBuild user is the same as user running Binder.
# https://docs.octave.org/interpreter/Administrating-Packages.html
# Use micromamba so that the compilers are properly found.
# https://gnu-octave.github.io/packages/
micromamba run -n notebook octave-cli --eval 'pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/io-2.6.4.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://github.com/apjanke/octave-tablicious/releases/download/v0.4.2/tablicious-0.4.2.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://github.com/gnu-octave/statistics/archive/refs/tags/release-1.6.5.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://github.com/gnu-octave/statistics-resampling/archive/refs/tags/5.5.7.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/struct-1.0.18.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://github.com/gnu-octave/pkg-control/releases/download/control-4.0.0/control-4.0.0.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/signal-1.4.5.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/optim-1.6.2.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://github.com/shsajjadi/OctaveCoder/releases/download/coder-1.9.1/coder-1.9.1.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/symbolic-3.1.1.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/miscellaneous-1.3.0.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/splines-1.3.5.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/strings-1.3.1.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/data-smoothing-1.3.0.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/ga-0.10.3.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/optiminterp-0.3.7.tar.gz"'
micromamba run -n notebook octave-cli --eval 'pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/dataframe-1.2.0.tar.gz"'

# Installation of R packages that are not avalable through conda-forge.
micromamba run -n notebook Rscript -e 'install.packages(c("lmboot","devEMF","psychmeta","esc","pCalibrate","HLMdiag","lm.beta","faux","plotthemes","clubSandwich","resample"), repos="https://cloud.r-project.org", lib="/srv/conda/envs/notebook/lib/R/library")'
micromamba run -n notebook Rscript -e 'remotes::install_github(c("profandyfield/adventr","acpennlab/discovr"))'
